// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class Clientes
{
    public int ID_Cliente { get; set; }

    public string Nombre { get; set; }

    public int ID_TipoCliente { get; set; }

    public string Dirección { get; set; }

    public string Teléfono { get; set; }

    public string Email { get; set; }

    public int ID_Zona { get; set; }

    public virtual TipoCliente ID_TipoClienteNavigation { get; set; }

    public virtual Zonas ID_ZonaNavigation { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();
}