// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class DETALLE
{
    public int id_detalle { get; set; }

    public int? id_venta { get; set; }

    public int? id_producto { get; set; }

    public int? cantidad { get; set; }

    public decimal? precio { get; set; }

    public virtual PRODUCTOS id_productoNavigation { get; set; }

    public virtual VENTA id_ventaNavigation { get; set; }
}