// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class Detalle_Pedido
{
    public int ID_Detalle { get; set; }

    public int ID_Pedido { get; set; }

    public int ID_Producto { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual Pedidos ID_PedidoNavigation { get; set; }

    public virtual Productos ID_ProductoNavigation { get; set; }
}