// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class EMPRESA
{
    public int id_empresa { get; set; }

    public string cedula_ruc { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<CONTACTO> CONTACTO { get; set; } = new List<CONTACTO>();

    public virtual ICollection<NOTIFICACION> NOTIFICACION { get; set; } = new List<NOTIFICACION>();

    public virtual ICollection<VENDEDOR> VENDEDOR { get; set; } = new List<VENDEDOR>();

    public virtual ICollection<VENTA> VENTA { get; set; } = new List<VENTA>();
}