// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class Entregas
{
    public int ID_Entrega { get; set; }

    public int ID_Pedido { get; set; }

    public int ID_Repartidor { get; set; }

    public DateTime FechaEntrega { get; set; }

    public string EstadoEntrega { get; set; }

    public string CoordenadasEntrega { get; set; }

    public virtual Pedidos ID_PedidoNavigation { get; set; }

    public virtual Usuarios ID_RepartidorNavigation { get; set; }
}