// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class Pedidos
{
    public int ID_Pedido { get; set; }

    public DateTime FechaPedido { get; set; }

    public string Estado { get; set; }

    public int ID_Cliente { get; set; }

    public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; } = new List<Detalle_Pedido>();

    public virtual ICollection<Entregas> Entregas { get; set; } = new List<Entregas>();

    public virtual Clientes ID_ClienteNavigation { get; set; }

    public virtual ICollection<Rutas> ID_Ruta { get; set; } = new List<Rutas>();
}