// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class PRECIOS
{
    public int id_precio { get; set; }

    public int? id_producto { get; set; }

    public int? id_usuario { get; set; }

    public decimal? precio { get; set; }

    public string detalle { get; set; }

    public virtual PRODUCTOS id_productoNavigation { get; set; }

    public virtual USUARIO id_usuarioNavigation { get; set; }
}