// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class PrecioProducto
{
    public int ID_Precio { get; set; }

    public int ID_Producto { get; set; }

    public DateOnly FechaDesde { get; set; }

    public decimal Precio { get; set; }

    public bool? Activo { get; set; }

    public virtual Productos ID_ProductoNavigation { get; set; }
}