// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class PRODUCTOS
{
    public int id_producto { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public string categoria { get; set; }

    public virtual ICollection<DETALLE> DETALLE { get; set; } = new List<DETALLE>();

    public virtual ICollection<PRECIOS> PRECIOS { get; set; } = new List<PRECIOS>();
}