// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class Rutas
{
    public int ID_Ruta { get; set; }

    public string NombreRuta { get; set; }

    public DateTime Fecha { get; set; }

    public int ID_Repartidor { get; set; }

    public virtual Usuarios ID_RepartidorNavigation { get; set; }

    public virtual ICollection<Pedidos> ID_Pedido { get; set; } = new List<Pedidos>();
}