// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class TipoCliente
{
    public int ID_TipoCliente { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();
}