// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class USUARIO
{
    public int id_usuario { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public bool? estado { get; set; }

    public DateOnly? ultimo_acceso { get; set; }

    public DateOnly? creado { get; set; }

    public virtual ICollection<PRECIOS> PRECIOS { get; set; } = new List<PRECIOS>();

    public virtual ICollection<VENDEDOR> VENDEDOR { get; set; } = new List<VENDEDOR>();

    public virtual ICollection<ROLES> id_rol { get; set; } = new List<ROLES>();
}