// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class Usuarios
{
    public int ID_Usuario { get; set; }

    public string NombreUsuario { get; set; }

    public string Contraseña { get; set; }

    public int ID_Rol { get; set; }

    public virtual ICollection<Entregas> Entregas { get; set; } = new List<Entregas>();

    public virtual Roles ID_RolNavigation { get; set; }

    public virtual ICollection<Rutas> Rutas { get; set; } = new List<Rutas>();
}