// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class VENDEDOR
{
    public int id_vendedor { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public string telefono { get; set; }

    public int? id_usuario { get; set; }

    public int? id_empresa { get; set; }

    public virtual ICollection<VENTA> VENTA { get; set; } = new List<VENTA>();

    public virtual EMPRESA id_empresaNavigation { get; set; }

    public virtual USUARIO id_usuarioNavigation { get; set; }
}