// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class VENTA
{
    public int id_venta { get; set; }

    public int? id_empresa { get; set; }

    public int? id_vendedor { get; set; }

    public string tipo_venta { get; set; }

    public DateOnly? fecha { get; set; }

    public decimal? total { get; set; }

    public string observaciones { get; set; }

    public virtual ICollection<DETALLE> DETALLE { get; set; } = new List<DETALLE>();

    public virtual EMPRESA id_empresaNavigation { get; set; }

    public virtual VENDEDOR id_vendedorNavigation { get; set; }
}