// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class Zonas
{
    public int ID_Zona { get; set; }

    public string NombreZona { get; set; }

    public string Ciudad { get; set; }

    public string Provincia { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();
}