// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class DulcefacilDBContext : DbContext
{
    public DulcefacilDBContext()
    {
    }

    public DulcefacilDBContext(DbContextOptions<DulcefacilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<Detalle_Pedido> Detalle_Pedido { get; set; }

    public virtual DbSet<Entregas> Entregas { get; set; }

    public virtual DbSet<Pedidos> Pedidos { get; set; }

    public virtual DbSet<PrecioProducto> PrecioProducto { get; set; }

    public virtual DbSet<Productos> Productos { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Rutas> Rutas { get; set; }

    public virtual DbSet<TipoCliente> TipoCliente { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    public virtual DbSet<Zonas> Zonas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-HQO5UAT\\SQLEXPRESS03;Initial Catalog=DulcefacilDB;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.ID_Cliente).HasName("PK__Clientes__E005FBFF6E5A5350");

            entity.Property(e => e.Dirección)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Teléfono)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_TipoClienteNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.ID_TipoCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Clientes__ID_Tip__4D94879B");

            entity.HasOne(d => d.ID_ZonaNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.ID_Zona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Clientes__ID_Zon__4E88ABD4");
        });

        modelBuilder.Entity<Detalle_Pedido>(entity =>
        {
            entity.HasKey(e => e.ID_Detalle).HasName("PK__Detalle___B3E0CED36E6F02CF");

            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_PedidoNavigation).WithMany(p => p.Detalle_Pedido)
                .HasForeignKey(d => d.ID_Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_P__ID_Pe__59FA5E80");

            entity.HasOne(d => d.ID_ProductoNavigation).WithMany(p => p.Detalle_Pedido)
                .HasForeignKey(d => d.ID_Producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_P__ID_Pr__5AEE82B9");
        });

        modelBuilder.Entity<Entregas>(entity =>
        {
            entity.HasKey(e => e.ID_Entrega).HasName("PK__Entregas__FEDACB7FA126A112");

            entity.Property(e => e.CoordenadasEntrega)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EstadoEntrega)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FechaEntrega).HasColumnType("datetime");

            entity.HasOne(d => d.ID_PedidoNavigation).WithMany(p => p.Entregas)
                .HasForeignKey(d => d.ID_Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entregas__ID_Ped__628FA481");

            entity.HasOne(d => d.ID_RepartidorNavigation).WithMany(p => p.Entregas)
                .HasForeignKey(d => d.ID_Repartidor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entregas__ID_Rep__6383C8BA");
        });

        modelBuilder.Entity<Pedidos>(entity =>
        {
            entity.HasKey(e => e.ID_Pedido).HasName("PK__Pedidos__FD76807057EC080A");

            entity.Property(e => e.Estado)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FechaPedido).HasColumnType("datetime");

            entity.HasOne(d => d.ID_ClienteNavigation).WithMany(p => p.Pedidos)
                .HasForeignKey(d => d.ID_Cliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pedidos__ID_Clie__571DF1D5");
        });

        modelBuilder.Entity<PrecioProducto>(entity =>
        {
            entity.HasKey(e => e.ID_Precio).HasName("PK__PrecioPr__00F3F740DB965A6B");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_ProductoNavigation).WithMany(p => p.PrecioProducto)
                .HasForeignKey(d => d.ID_Producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PrecioPro__ID_Pr__5441852A");
        });

        modelBuilder.Entity<Productos>(entity =>
        {
            entity.HasKey(e => e.ID_Producto).HasName("PK__Producto__9B4120E2859719B6");

            entity.Property(e => e.Descripción).HasColumnType("text");
            entity.Property(e => e.NombreProducto)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.ID_Rol).HasName("PK__Roles__202AD220B80D3151");

            entity.Property(e => e.NombreRol)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Rutas>(entity =>
        {
            entity.HasKey(e => e.ID_Ruta).HasName("PK__Rutas__4851E68B4557769C");

            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.NombreRuta)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_RepartidorNavigation).WithMany(p => p.Rutas)
                .HasForeignKey(d => d.ID_Repartidor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Rutas__ID_Repart__66603565");

            entity.HasMany(d => d.ID_Pedido).WithMany(p => p.ID_Ruta)
                .UsingEntity<Dictionary<string, object>>(
                    "Ruta_Pedido",
                    r => r.HasOne<Pedidos>().WithMany()
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Ruta_Pedi__ID_Pe__6A30C649"),
                    l => l.HasOne<Rutas>().WithMany()
                        .HasForeignKey("ID_Ruta")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Ruta_Pedi__ID_Ru__693CA210"),
                    j =>
                    {
                        j.HasKey("ID_Ruta", "ID_Pedido").HasName("PK__Ruta_Ped__57868E8CD87EE35F");
                    });
        });

        modelBuilder.Entity<TipoCliente>(entity =>
        {
            entity.HasKey(e => e.ID_TipoCliente).HasName("PK__TipoClie__C0F4EA7CCAF6ABC2");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.ID_Usuario).HasName("PK__Usuarios__DE4431C53167EE2D");

            entity.Property(e => e.Contraseña)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_RolNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.ID_Rol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Usuarios__ID_Rol__5FB337D6");
        });

        modelBuilder.Entity<Zonas>(entity =>
        {
            entity.HasKey(e => e.ID_Zona).HasName("PK__Zonas__81349323AB383065");

            entity.Property(e => e.Ciudad)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NombreZona)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Provincia)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}