// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dulcefacil.Infraestructura.AccesoDatos;

public partial class DulcefacilDBContext : DbContext
{
    public DulcefacilDBContext()
    {
    }

    public DulcefacilDBContext(DbContextOptions<DulcefacilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }

    public virtual DbSet<CONTACTO> CONTACTO { get; set; }

    public virtual DbSet<DETALLE> DETALLE { get; set; }

    public virtual DbSet<EMPRESA> EMPRESA { get; set; }

    public virtual DbSet<NOTIFICACION> NOTIFICACION { get; set; }

    public virtual DbSet<PRECIOS> PRECIOS { get; set; }

    public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }

    public virtual DbSet<ROLES> ROLES { get; set; }

    public virtual DbSet<USUARIO> USUARIO { get; set; }

    public virtual DbSet<VENDEDOR> VENDEDOR { get; set; }

    public virtual DbSet<VENTA> VENTA { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-HQO5UAT\\SQLEXPRESS03;Initial Catalog=DulcefacilDB;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ACTIVIDAD>(entity =>
        {
            entity.HasKey(e => e.id_actividad).HasName("PK__ACTIVIDA__DCD34883D9EDA6B8");

            entity.Property(e => e.id_actividad).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.tipo_venta)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<CONTACTO>(entity =>
        {
            entity.HasKey(e => e.id_contacto).HasName("PK__CONTACTO__099A52B864C00FCF");

            entity.Property(e => e.id_contacto).ValueGeneratedNever();
            entity.Property(e => e.apellido)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.identificacion)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.id_empresaNavigation).WithMany(p => p.CONTACTO)
                .HasForeignKey(d => d.id_empresa)
                .HasConstraintName("FK__CONTACTO__id_emp__412EB0B6");
        });

        modelBuilder.Entity<DETALLE>(entity =>
        {
            entity.HasKey(e => e.id_detalle).HasName("PK__DETALLE__4F1332DE4A690632");

            entity.Property(e => e.id_detalle).ValueGeneratedNever();
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.DETALLE)
                .HasForeignKey(d => d.id_producto)
                .HasConstraintName("FK__DETALLE__id_prod__52593CB8");

            entity.HasOne(d => d.id_ventaNavigation).WithMany(p => p.DETALLE)
                .HasForeignKey(d => d.id_venta)
                .HasConstraintName("FK__DETALLE__id_vent__5165187F");
        });

        modelBuilder.Entity<EMPRESA>(entity =>
        {
            entity.HasKey(e => e.id_empresa).HasName("PK__EMPRESA__4A0B7E2C4567D7BD");

            entity.Property(e => e.id_empresa).ValueGeneratedNever();
            entity.Property(e => e.cedula_ruc)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<NOTIFICACION>(entity =>
        {
            entity.HasKey(e => e.id_notificacion).HasName("PK__NOTIFICA__8270F9A55AD0B6EF");

            entity.Property(e => e.id_notificacion).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.id_actividadNavigation).WithMany(p => p.NOTIFICACION)
                .HasForeignKey(d => d.id_actividad)
                .HasConstraintName("FK__NOTIFICAC__id_ac__571DF1D5");

            entity.HasOne(d => d.id_empresaNavigation).WithMany(p => p.NOTIFICACION)
                .HasForeignKey(d => d.id_empresa)
                .HasConstraintName("FK__NOTIFICAC__id_em__5812160E");
        });

        modelBuilder.Entity<PRECIOS>(entity =>
        {
            entity.HasKey(e => e.id_precio).HasName("PK__PRECIOS__A70EF6ED566178AA");

            entity.Property(e => e.id_precio).ValueGeneratedNever();
            entity.Property(e => e.detalle)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.PRECIOS)
                .HasForeignKey(d => d.id_producto)
                .HasConstraintName("FK__PRECIOS__id_prod__45F365D3");

            entity.HasOne(d => d.id_usuarioNavigation).WithMany(p => p.PRECIOS)
                .HasForeignKey(d => d.id_usuario)
                .HasConstraintName("FK__PRECIOS__id_usua__46E78A0C");
        });

        modelBuilder.Entity<PRODUCTOS>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__PRODUCTO__FF341C0D8E639D2C");

            entity.Property(e => e.id_producto).ValueGeneratedNever();
            entity.Property(e => e.categoria)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.descripcion)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ROLES>(entity =>
        {
            entity.HasKey(e => e.id_rol).HasName("PK__ROLES__6ABCB5E009D74020");

            entity.Property(e => e.id_rol).ValueGeneratedNever();
            entity.Property(e => e.tipo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<USUARIO>(entity =>
        {
            entity.HasKey(e => e.id_usuario).HasName("PK__USUARIO__4E3E04ADEABC427F");

            entity.Property(e => e.id_usuario).ValueGeneratedNever();
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasMany(d => d.id_rol).WithMany(p => p.id_usuario)
                .UsingEntity<Dictionary<string, object>>(
                    "USUARIO_ROL",
                    r => r.HasOne<ROLES>().WithMany()
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__USUARIO_R__id_ro__3C69FB99"),
                    l => l.HasOne<USUARIO>().WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__USUARIO_R__id_us__3B75D760"),
                    j =>
                    {
                        j.HasKey("id_usuario", "id_rol").HasName("PK__USUARIO___5895CFF36A6B9C55");
                    });
        });

        modelBuilder.Entity<VENDEDOR>(entity =>
        {
            entity.HasKey(e => e.id_vendedor).HasName("PK__VENDEDOR__0093030847063196");

            entity.Property(e => e.id_vendedor).ValueGeneratedNever();
            entity.Property(e => e.apellido)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.id_empresaNavigation).WithMany(p => p.VENDEDOR)
                .HasForeignKey(d => d.id_empresa)
                .HasConstraintName("FK__VENDEDOR__id_emp__4AB81AF0");

            entity.HasOne(d => d.id_usuarioNavigation).WithMany(p => p.VENDEDOR)
                .HasForeignKey(d => d.id_usuario)
                .HasConstraintName("FK__VENDEDOR__id_usu__49C3F6B7");
        });

        modelBuilder.Entity<VENTA>(entity =>
        {
            entity.HasKey(e => e.id_venta).HasName("PK__VENTA__459533BFC9A0974C");

            entity.Property(e => e.id_venta).ValueGeneratedNever();
            entity.Property(e => e.observaciones)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.tipo_venta)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_empresaNavigation).WithMany(p => p.VENTA)
                .HasForeignKey(d => d.id_empresa)
                .HasConstraintName("FK__VENTA__id_empres__4D94879B");

            entity.HasOne(d => d.id_vendedorNavigation).WithMany(p => p.VENTA)
                .HasForeignKey(d => d.id_vendedor)
                .HasConstraintName("FK__VENTA__id_vended__4E88ABD4");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}